### ISSUE TITLE
Lighthouse CI `NO_FCP` Error After Upgrading to v1.15.0+

### ISSUE THREAD

**Issue by jzolnowski** [analogjs/analog#1685]
### Please provide the environment you discovered this bug in.

Dependency Versions:

```json
"dependencies": {
  ...
  "@analogjs/content": "1.15.1",
  "@analogjs/router": "1.15.1",
  "@nx/angular": "20.7.2",
  "marked": "^15.0.7",
  "marked-gfm-heading-id": "^4.1.1",
  "marked-highlight": "^2.2.1",
  "marked-mangle": "^1.1.10",
}},
  "devDependencies": {
  "@analogjs/platform": "1.15.1",
  "@analogjs/vite-plugin-angular": "1.15.1",
  "@nx/devkit": "20.7.2",
  "@nx/vite": "20.7.2",
  ...
}
```

Lighthouse CI job configuration on CircleCI:

```
job_defaults: &job_defaults
  working_directory: ~/working_directory
  docker:
    - image: cimg/node:lts-browsers

lighthouse:
  <<: *job_defaults
  steps:
    - browser-tools/install-chrome
    - setup
    - run:
      name: 'Lighthouse CI'
      command: |
        npm install --prefix=$HOME/.local -g @lhci/cli@0.14.0
        lhci autorun
    - store_artifacts:
      path: ./.lighthouseci
```

### Which area/package is the issue in?

Don't know / other

### Description

Hi, 
I've encountered a regression with [Lighthouse CI - `@lhci/cli@0.14.0`](https://github.com/GoogleChrome/lighthouse-ci) tool after upgrading AnalogJS from `v1.14.1` to `v1.15.0` (the issue persists also in v1.15.1). 

In version 1.14.1, our Lighthouse CI job on CircleCI was running successfully (with the same CircleCI configuration). However, after the upgrade to AnalogJS `v1.15.0` (along with all its deps), I consistently receive the following error: `Runtime error encountered: The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)`. Looks like the Lighthouse is unable to detect the FCP, suggesting that the page might not be rendering any visible content within the expected timeframe. It's unclear at this point what is causing this regression.

I have not yet identified a workaround for this issue other than downgrading to AnalogJS `v1.14.1`, which is not a long-term solution.

Could you please investigate this issue?

Thank you!

### Please provide the exception or error you saw

```true
`Runtime error encountered: The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)`

![Image](https://github.com/user-attachments/assets/f6dc7c5d-2d36-4c0b-93fd-5b5af5c116fd)
```

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No
